Description: Template for Iris underlying infrastructure, including VPC and related network settings, RDS DB cluster, and Cognito pool and app client.

Parameters:
  Environment:
    Description: "Specify the Environment type of the stack."
    Type: String
    AllowedValues:
      - feat
      - staging
      - prod

Conditions:
  Production: !Equals
    - !Ref Environment
    - prod

###########
### VPC ###
###########

Resources:
  ###############
  ### Cognito ###
  ###############

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "patient-${Environment}"
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: birthdate
          Required: true
        - Name: practiceid
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: patientid
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: departmentid
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: departmentcontact
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: termsAndCondTime
          AttributeDataType: DateTime
          DeveloperOnlyAttribute: false
          Mutable: true
        - Name: edd
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: postpartum_end_date
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: enterpriseid
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: profilelist
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
        - Name: lastlogintime
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 256
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: '''<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Verification Code</title> </head> <body> <div style=" /* width: 636px; */ margin: auto; text-align: left; border-radius: 10px; border: 1px solid #e9e9e9; overflow: hidden; "> <div style="background: rgba(74, 106, 126, 1); padding: 16px 24px 15px 24px;"> <img src="https://lh3.googleusercontent.com/fife/AKsag4M5rhL9ic3QIKMoO0sWJAhDajfwI7rRxzSR1kBJvlKthq2e3-isLq5dN_RPLb_aC6ZUuHY6SREzDbWbPppvP0eNdABulxec6re9vuaZCwb5WAAbELLQt_Q1Lx_gdGjlb-BzmiwA2nckFVuCCyMCf15Ps7KjDb7SEgwhrimKbsPQ9TlgC-LmJm3_IbvsxNeFo1Mw_TSPufWgOq_fUxOo8N4hAaD8uKI8a-3iTqztKSNcibk6NEaM6lh78ZgS9jiY5Q7ZKGot_r-75GxB3m6mxJs4ctFCZtuhPbxPtlcB3rQYDfQm7xVlZ1Ozy8ldPvFIAgSfa1FO01GH1PC6Eh2Xdw1tYYmalTzPuKNqYM5AS_oQ8_nqBhTuWZR4pxA4St_2xWKZq-jbMrmB9nXyCi2HfLQzV1KoXgNKvNM8G0rrTv-VwjdFRXZpVe5mPLNuXksvYKv9etUNNUzXdvmCcmEl7Njn8a88jRI3F0XtcXXGnSK8uueWkUy0fvs69HI3qK-vsZ3uyqfKX4yi7QysDYh_rChshjGanvqcODwvDyZtHWM2LuygbeMchJWo78AQ86HOlN7Fs7Lzda7isWge1ihBX3_kvJnPiX9t9fzZBHnlICu14osJ8ike7KIsRYw8BkjARF64lLr6-c3zw7jX-ORZ5A9ritOLscuRcQYWY1RdfhRxsHbNzoUIyYZ47GjOtJ_gXED3xGYvrI3d-Lu944-7rlqsYCOq6lOaksBsvw_MazulweQses0rSizxORyjsMqx4pnzGpv9_F3uoeQwByJkrfiAF7ha6UlXPG1oHujlEdFkmDqf3vVJcP5P1EvUFaq0et4F9wlI7U8ZW_3Y-mfhGphoW7yMD03bUi_HicQeyeTPngJJAuS6NwXcuwTYJS-aC9KgAw_2WELGrsWCgs_ZpuUHEfBORKH2yusaDA0bDdzuQ9rudSh03t9rTah8Ch48WbA4eXRe-wJt-QwVOPVucF-MwLoDTak4hKdHsvqh36_TUWqWcyr-DVL16OljSY6RJGQlEZSTxYrLVzceKYZ7lrLhUIhhY5TRThNMu9Y3yuRob-65q4Rv5djzvAYd0myyTaywFCqe00OY9MbnTzPBKPI8v9Q2IG2QjBA7aEM002XBCsJYzRWK_Z56fc52keVC6TDRQb-Hl52fRppbwuyX8lPfLepgGHaxx0YIODs82v_2tq_onOx2Av0XhpHGi5JQNWSk2w1H7twoFSwj3H0b7J5_Z0WuusjYH_43XZDvBo_X9N-zVqCXdFnccTdCLGPmfBBd7IVbAS44dvd8OgtSH_cUo9DI0Lw7LuhpKAhG_7gKH86JHT01O6dzPg554tyF07r4KxyuSc5RQDibsnTvmChJtA5mA5v8N075ut-ZsMx0HMFpFKja39ydP5xExpmNTXq0ZOIUYts-XdOrOV7UHtP67TFOvs3SjYrOFNfmbenjjQqfot05tbzlkVtG9B5Uu8QadRGumwmJ_pmCqfY8EFa2pZH71KvxgdW8AHzvNlwL89qflQhTRU3kIvik1A2pFfQjUwi38Vpt9ADbuqKWJ2ornhybDyFa9dMQeI7X2l48Hw=w2048-h1061" height="18" alt="Diana Health Logo" /> </div> <div style=" padding: 20px 28px 20px 24px; line-height: 20px; "> <div style="line-height: 20px; margin-bottom: 15px;"> Hello! </div> <div style="line-height: 20px; margin-bottom: 15px;"> Here’s your one-time verification code you requested from the Diana Health app. </div> <div style="line-height: 20px; margin-bottom: 15px;"> This code will remain valid for 7 days and can only be used once. </div> <div style="margin-bottom: 20px;"> <b>{####}</b> </div> <div style="line-height: 20px; margin-bottom: 15px;"> If you didn’t request this code, you can ignore this message. Please email support@diana.health with any questions or concerns. </div> <div style="line-height: 20px; margin-bottom: 15px;"> If you experience problems accessing your account, please read through our <a style="color: rgba(17, 85, 204, 1);" href="https://drive.google.com/file/d/1ecfFNnzzvHSeV6BbVsx2gNMV6iGPEryY/view?usp=sharing" tarhet="_blank">troubleshooting FAQs.</a> If you’re still experiencing an issue, please complete <a style="color: rgba(17, 85, 204, 1);" href="https://docs.google.com/forms/d/e/1FAIpQLSeiAP6GDqTCP1chZz1ZXmHFPqSP9igiooCW-CVA-nPvAU67tg/viewform?usp=sf_link?" target="_blank">this survey</a> and a member of our team will reach out to you shortly. You can also email us directly at <a style="color: rgba(17, 85, 204, 1);" href="mailto:support@diana.health" target="email">support@diana.health</a>. </div> <div style="line-height: 20px; margin-bottom: 15px;"> Thank you for being a part of our Diana Health family! </div> <div style="line-height: 20px; margin-bottom: 15px;"> <i style="color: rgba(161, 161, 161, 1);"> Please do not reply to this email. It was sent from an unmonitored inbox. The email and its contents are only intended for use by the named addressee. If you are not the intended recipient of this email or received this message in error, please inform Diana Health at support@diana.health, then immediately and permanently delete this email. </i> </div> </div> </div> </body> </html>'''

        EmailSubject: "Diana Health Verification Code"

  # Lambda configuration can only be done after the application stack has been deployed,
  # will leave it to be manually configured for now

  CognitoPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Sub "zita-${Environment}" # Will be used as a prefix to .auth.us-east-1.amazoncognito.com

  CognitoAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 1
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - openid
        - aws.cognito.signin.user.admin
        - profile
      CallbackURLs:
        - https://oauth.pstmn.io/v1/callback
      LogoutURLs:
        - https://oauth.pstmn.io/v1/callback
      ClientName: mobile-app
      EnableTokenRevocation: true
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      IdTokenValidity: 1
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref CognitoUserPool
      ReadAttributes:
        - address
        - birthdate
        - "custom:departmentid"
        - "custom:edd"
        - "custom:postpartum_end_date"
        - "custom:patientid"
        - "custom:departmentcontact"
        - "custom:practiceid"
        - "custom:termsAndCondTime"
        - "custom:enterpriseid"
        - "custom:profilelist"
        - "custom:lastlogintime"
        - email
        - email_verified
        - family_name
        - gender
        - given_name
        - locale
        - middle_name
        - name
        - nickname
        - phone_number
        - phone_number_verified
        - picture
        - preferred_username
        - profile
        - updated_at
        - website
        - zoneinfo
      WriteAttributes:
        - address
        - birthdate
        - "custom:practiceid"
        - "custom:patientid"
        - "custom:departmentcontact"
        - "custom:departmentid"
        - "custom:termsAndCondTime"
        - "custom:postpartum_end_date"
        - "custom:edd"
        - "custom:enterpriseid"
        - "custom:profilelist"
        - "custom:lastlogintime"
        - email
        - family_name
        - gender
        - given_name
        - locale
        - middle_name
        - name
        - nickname
        - phone_number
        - picture
        - preferred_username
        - profile
        - updated_at
        - website
        - zoneinfo

  ##############
  ###  Docs  ###
  ##############

  SwaggerBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub access-identity-${Environment}.s3.${AWS::Region}.amazonaws.com

  SwaggerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub zita-swagger-${Environment}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  SwaggerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SwaggerBucket
      PolicyDocument:
        Version: "2008-10-17"
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join
              - ""
              - - !GetAtt SwaggerBucket.Arn
                - /*
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${SwaggerBucketOriginAccessIdentity.Id}"

  SwaggerCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: !Sub s3-origin-zita-swagger-${Environment}
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # AWS-provided policy for Optimized Caching
          OriginRequestPolicyId: "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf" # AWS-provided policy for CORS
          ResponseHeadersPolicyId: "eaab4381-ed33-4a86-88ca-d9558dc6cd63" # AWS-provided policy for CORS and preflight
          ViewerProtocolPolicy: allow-all
        Origins:
          - Id: !Sub s3-origin-zita-swagger-${Environment}
            DomainName: !GetAtt SwaggerBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${SwaggerBucketOriginAccessIdentity}"

Outputs:
  CognitoPoolId:
    Description: Reference to the Cognito User Pool Id
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "${AWS::StackName}-CognitoPoolId"

  CognitoAppClient:
    Description: Reference to the Cognito User Pool App Client Id
    Value: !Ref CognitoAppClient
    Export:
      Name: !Sub "${AWS::StackName}-CognitoAppClient"

  SwaggerCloudFrontDistributionId:
    Description: The ID of the CloudFront distribution
    Value: !GetAtt SwaggerCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-SwaggerCloudFrontDistributionId"
