name: 22 Zita Prod
on:
  release:
    types:
      - released
      # On manual trigger
  workflow_dispatch:

jobs:
  build-deploy:
    name: Deploy Zita with SAM
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Set up SAM
        uses: aws-actions/setup-sam@v1
        with:
          version: 1.37.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LIVE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare variables for SAM
        id: ssm_params
        run: |
          ZITA_ENV=prod
          DB_NAME=zita

          PARAMS="ParameterKey=Environment,ParameterValue=${ZITA_ENV}"

          echo BRANCH_NAME=$BRANCH_NAME >> $GITHUB_ENV
          echo ZITA_ENV=$ZITA_ENV >> $GITHUB_ENV
          echo PARAMS=$PARAMS >> $GITHUB_ENV

      - name: SAM build
        run: sam build --use-container --template deploy/zita-template.yaml --config-file deploy/samconfig-prod.toml

      - name: SAM deploy
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name diana-zita-$ZITA_ENV \
          --config-file deploy/samconfig-prod.toml --debug \
          --parameter-overrides ${PARAMS}